Repository hmcts/probate-business-service, pull requests merged in 2019-09, with the labels that each got.

#145 Pro 5526 fix accents bug
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/probate/services/invitation/InvitationService.java
  src/main/java/uk/gov/hmcts/probate/services/invitation/controllers/InvitationController.java
  src/main/java/uk/gov/hmcts/probate/services/invitation/model/Invitation.java
  src/test/java/uk/gov/hmcts/probate/services/invitation/unit/InvitationServiceTest.java
  src/test/resources/invitation/expectedDecoding.json
  src/test/resources/invitation/success.json
Labels: ns:probate-business-service-pr-145

#155 Disable Legacy Deployment
  Jenkinsfile_CNP
Labels: ns:probate-business-service-pr-155

#154 clean up probate webapps
  infrastructure/.terraform-version
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/variables.tf
Labels: ns:probate-business-service-pr-154
