Repository hmcts/probate-business-service, pull requests merged in 2020-11, with the labels that each got.

#435 Update commons to 1.1.0.2
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-435

#438 TA-166 Consumer pact for interaction with PdfService
  Jenkinsfile_CNP
  build.gradle
  src/contractTest/java/uk/gov/hmcts/probate/services/businessdocuments/controllers/BusinessDocumentControllerProviderTest.java
  src/contractTest/java/uk/gov/hmcts/probate/services/businessdocuments/controllers/InvitationControllerProviderTest.java
  src/contractTest/java/uk/gov/hmcts/probate/services/consumer/DocumentServiceConsumerTest.java
  src/contractTest/java/uk/gov/hmcts/probate/services/consumer/PdfServiceConsumerTest.java
  src/contractTest/resources/application.properties
  src/contractTest/resources/application.yml
  src/contractTest/resources/logback.xml
  src/main/java/uk/gov/hmcts/probate/services/businessdocuments/services/PDFGenerationService.java
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-438

#443 TA-166: Add suppression for junit
  Jenkinsfile_CNP
  config/owasp/suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-443
