Repository hmcts/probate-business-service, pull requests merged in 2020-09, with the labels that each got.

#397 Pro 7827 serenity implementation
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  build.gradle
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/probate/functional/BulkScanCoverSheetPDFTest.java
  src/functionalTest/java/uk/gov/hmcts/probate/functional/BusinessDocumentControllerTest.java
  src/functionalTest/java/uk/gov/hmcts/probate/functional/BusinessServiceBusinessValidationControllerTests.java
  src/functionalTest/java/uk/gov/hmcts/probate/functional/BusinessServiceDocumentControllerTests.java
  src/functionalTest/java/uk/gov/hmcts/probate/functional/BusinessServiceInvitationControllerTests.java
  src/functionalTest/java/uk/gov/hmcts/probate/functional/BusinessServicePinControllerTests.java
  src/functionalTest/java/uk/gov/hmcts/probate/functional/BusinessServiceServiceAuthTokenGenerator.java
  src/functionalTest/java/uk/gov/hmcts/probate/functional/CheckSummaryAnswerPDFTest.java
  src/functionalTest/java/uk/gov/hmcts/probate/functional/IntegrationTestBase.java
  src/functionalTest/java/uk/gov/hmcts/probate/functional/LegalDeclarationPDFTest.java
  src/functionalTest/java/uk/gov/hmcts/probate/functional/PDFIntegrationBase.java
  src/functionalTest/resources/application.properties
  src/functionalTest/resources/json/validLegalDeclaration.json
  src/functionalTest/resources/json/validLegalDeclarationForMultipleExecutors.json
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-397

#423 Add development environment
  .env
  README.md
  docker-compose.yml
  docker/database/Dockerfile
  docker/database/create-multiple-postgres-database.sh
  src/main/resources/application.yml
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-423

#424 update dev env
  README.md
  docker-compose.yml
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-424
