Repository hmcts/probate-business-service, pull requests merged in 2020-10, with the labels that each got.

#426 terraform update
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/state.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-426

#428 DTSPB-631 Owasp version upgrade
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-428

#413 PRO-7900: upgrade to probate commons 1.1 for java 11 upgrade
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-413
