Repository hmcts/probate-business-service, pull requests merged in 2021-04, with the labels that each got.

#509 DTSPB-1775 updated commons version
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-509

#520 DTSPB-1843 Updated the Java chart version
  charts/probate-business-service/Chart.yaml
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-520

#523 DTSPB-1895 Fix CVE vulnerability and Master build
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-523

#524 upgrade bintray to jitpack
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-524
