Repository hmcts/probate-business-service, pull requests merged in 2021-11, with the labels that each got.

#614 DTSPB-2450 fix spring core cve
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-614

#615 Commons changes for will and codicils condition
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-615

#616 Dtspb 2454 ee first page
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-616

#617 DTSPB-2482: Legal statement change for excepted estate
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-617
