Repository hmcts/probate-business-service, pull requests merged in 2021-08, with the labels that each got.

#601 Dtspb 2066 fortify fixes
  src/main/java/uk/gov/hmcts/probate/services/businessdocuments/services/FileSystemResourceService.java
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-601

#599 Integrate Fortify with Jenkins
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-599

#603 suppress CVE until spring boot upgrade
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-603

#602 DTSPB-2276 - Bump chart.yaml java version to 3.6.0
  charts/probate-business-service/Chart.yaml
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-602

#605 New commons tag for TC
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-605
