Repository hmcts/probate-business-service, pull requests merged in 2022-07, with the labels that each got.

#653 DTSPB-2896 suppress log4j cve
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-653

#655 DTSPB-2943 - update the version
  charts/probate-business-service/Chart.yaml
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-655

#656 DTSPB-2858 point to new comons
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-656

#647 DTSPB-1714: upgraded commons
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-647
