Repository hmcts/probate-business-service, pull requests merged in 2022-10, with the labels that each got.

#663 DTSPB-3033 suppress CVE-2022-38752
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-663

#668 DTSPB-3039 suppress CVE-2022-42003,CVE-2022-42004
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-668

#667 DTSPB-2997 hand off flag point to new commons
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-667

#670 DTSPB-3100: removed s2s PACT tests
  src/contractTest/java/uk/gov/hmcts/probate/services/consumer/ServiceAuthConsumerDetailTest.java
  src/contractTest/java/uk/gov/hmcts/probate/services/consumer/ServiceAuthConsumerLeaseTest.java
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-670

#665 DTSPB-2407-PA8A-and-DTSPB-2656-PA8B: update probate commons
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-665
