Repository hmcts/probate-business-service, pull requests merged in 2022-05, with the labels that each got.

#637 DTSPB-247 resend email to exec
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-637

#641 DTSPB-2781: commons upgrade
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-641

#642 Autoscaling Update Chart.yaml
  charts/probate-business-service/Chart.yaml
  charts/probate-business-service/values.yaml
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-642

#644 DTSPB-2799: Fix CVE-2016-1000027 Vulnerability For probate-submit-ser…
  charts/probate-business-service/Chart.yaml
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-644

#643 DTSPB-2705 dod equals dob
  build.gradle
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-643

#645 DTSPB-2081: solve cve
  build.gradle
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-645

#640 DTSPB-2672: implementing Open ID Connect (OICD)
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-640
