Repository hmcts/probate-business-service, pull requests merged in 2022-02, with the labels that each got.

#623 DTSPB-2584: Resolve the below deprecated warning form Java repos
  charts/probate-business-service/Chart.yaml
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-623

#624 DTSPB-2586 Fix Vulnerabilities
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-624

#627 DTSPB-2604 Remove the not needed transitive dependency
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-627
