Repository hmcts/probate-business-service, pull requests merged in 2022-04, with the labels that each got.

#636 DTSPB-2704: Upgrade Springboot version 2.6.6 for probate services
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-636

#639 DTSPB-2747 Fix CVE-2022-22968
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-639

#638 Dtspb 2544 pp notorial access
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-638
