Repository hmcts/probate-business-service, pull requests merged in 2023-12, with the labels that each got.

#759 DTSPB-3819 surpress CVE
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-759

#761 DTSPB-3930 update suppressions
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-761

#762 DTSPB-3929 Remove OWASP Dependency Check
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-762

#756 DTSPB-3645 added the API key from hardcoded value .
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  charts/probate-business-service/values.preview.template.yaml
  src/contractTest/resources/application.yml
  src/functionalTest/resources/json/inviteDataValid.json
  src/main/resources/application.yml
  src/test/java/uk/gov/hmcts/probate/services/pin/integration/PinControllerTest.java
  src/test/resources/application.yml
Labels: ns:probate, prd:probate, enable_keep_helm, rel:probate-business-service-pr-756

#760 DTSPB-3925 updated the service auth provider
  .aat-env
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/probate/functional/BusinessServiceInvitationControllerTests.java
  src/main/java/uk/gov/hmcts/probate/BusinessApplication.java
  src/main/java/uk/gov/hmcts/probate/services/pin/PinService.java
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-760
