Repository hmcts/probate-business-service, pull requests merged in 2025-08, with the labels that each got.

#1114 DTSPB-4368: Remove swagger config
  build.gradle
Labels: ns:probate, prd:probate, enable_keep_helm, nightly, rel:probate-business-service-pr-1114

#1126 DTSPB-4936: Add explicit Tomcat to fix CVE
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-1126

#1133 DTSPB-4661 bump commons
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-business-service-pr-1133
